@startuml

class Person {
    id: Integer
    name: String

    setName(name: String): void
    getName(): String
}

class Person2 {
    id: Integer
    name: String

    setName(name: String): void
    getName(): String
}

@enduml